# Generated by Django 3.2 on 2023-04-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_artwork_medium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='title',
            new_name='name',
        ),
    ]
